### ISSUE TITLE
A question 

### ISSUE THREAD

**Issue by dheeraj-326** [waterrmalann/kards#23]
Hi Alan, I heard about you from a Brototype student I know. You were spoken about as if you are a legend. So I was curious and went exploring your github when I came across this repo.

Just one question: Your description mentions that all data is stored locally by the browser. But the primary goal of such a tool is collaboration between team members. If the source of truth of data (task status, description etc) is session or some other local storage, how is this possible?

Please don't take this as a criticism and its not. I have respect for your hardwork and passion. I looked at some other of your repos as well

**Comment by waterrmalann** [comment]
Hello Dheeraj,

I feel like this really isn't the place for non-development related queries. You can always message me at my email or telegram which I've listed rather than here but anyways, 

Would love to know whoever referred to me as if I were a legend 😂 I think that's a little too heavy of a term to live upto. 

This was an experimental side project that I've built a really long time ago, even before my Brototype days. Yes it does not have real time collaboration because that was really not what I was building. If you notice, the whole thing does not depend on any frameworks or libraries and is fully vanilla Javascript. From the drag and drop, to the multi board system everything was built from scratch and that caused a lot of headache for me but it was also a valuable experience which taught me a lot. 

The data is locally stored, I believe I haven't mentioned anything about real time collaboration for this project. I do not think a kanban board app necessarily needs team collaboration in my opinion as I do use them for personal task management. 

I do plan to revisit this concept of building a pure vanilla app and try to make this again with live collaboration sometime in the near future, but preferably not within this same repository as it has sort of become unmaintainable with all the technical debt. I feel like I've learnt a lot since then which would be beneficial to something like this. 

Again, thanks for stopping by! Very rarely anyone leaves a comment or a query on what I do, feel free to ping me at my mail or telegram if you wish to know more..

Regards,
Alan.

**Comment by dheeraj-326** [comment]
Snobbery is indeed the path to success. Keep at it. I wish you best, young man.

**Comment by waterrmalann** [comment]
Hello again,

Just to keep things clear: I sincerely did not mean any offense. I genuinely wish to understand. 

I believe I responded professionally and appropriately to your query. I really do not understand why you would leave such a remark. 

You asked something about my project and I really love talking to people who are curious about what I do. Perhaps I wrote a little too much? I apologize for being passionate about what I do.

Respectfully,
Alan.
